config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'home#index'
  mount Sidekiq::Web => '/sidekiq'
  resources :decks do
    post :search
    get :card_types
    get :mana_curve
    get :color_distribution
  end
  resources :drafts
  resources :lobbies

  resources :boosters do
    post :export, on: :member
  end

  resources :sealeds do
    post :export, on: :member
  end

  resources :cards

  get 'auth/google', to: redirect('/auth/google_oauth2')
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/booster.rb
class Booster < ApplicationRecord
  belongs_to :card_set, optional: true
  belongs_to :draft, optional: true

  has_many :cards, dependent: :destroy
end

app/controllers/boosters_controller.rb
class BoostersController < ApplicationController
  def new
    @sets = CardSet.where(set_type: 'expansion').order(release_date: :desc)
    @booster = Booster.new
  end

  def show
    @booster = Booster.find(params[:id])
  end

  def create
    booster = Boosters::Create.new(set_id).perform

    redirect_to booster
  end

  def export
    cards = Card.where(id: cards_for_export)
    @cards = Exporters::Text.perform(cards)

    render 'common/export'
  end

  private

  def booster_params
    params.require(:booster).permit(:card_set_id) 
    params[:booster]
  end

  def set_id
    booster_params[:card_set_id]
  end

  def cards_for_export
    params.keys.map do |key|
      key.gsub("checkbox_", "")
    end 
  end
end

app/views/boosters/new.html.erb
<h2>Generate Booster</h2>
<%= form_for @booster do |f| %>
  <%= f.collection_select :card_set_id, @sets, :id, :name, {}, class: "ui search dropdown" %>
  <br />
  <br />
  <%= f.button class: "ui black button" %>
<% end %>

app/views/boosters/show.html.erb
<%= form_for @booster, url: export_booster_path(@booster), method: 'post' do |f| %>
  <div style='float: right; padding-top: 15px'>
    <%= submit_tag 'Exportar para TXT' %>
  </div>
  <%= render 'common/card', cards: @booster.cards %>
<% end %>