config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'home#index'
  mount Sidekiq::Web => '/sidekiq'
  resources :decks do
    post :search
    get :card_types
    get :mana_curve
    get :color_distribution
  end
  resources :drafts
  resources :lobbies

  resources :boosters do
    post :export, on: :member
  end

  resources :sealeds do
    post :export, on: :member
  end

  resources :cards

  get 'auth/google', to: redirect('/auth/google_oauth2')
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/sealed.rb
class Sealed < ApplicationRecord
  has_many :card_set
  has_many :cards, dependent: :destroy

  def ordered_cards
    cards.order(:colors, :cmc, :name)
  end
end

app/controllers/sealeds_controller.rb
class SealedsController < ApplicationController
  def new
    @sets = CardSet.where(set_type: 'expansion').order(release_date: :desc)
  end

  def show
    @sealed = Sealed.find(params[:id])
    @cards = @sealed.ordered_cards
  end

  def create
    sealed = Sealed.create
    @cards = Sealeds::Create.perform(card_sets, sealed)

    redirect_to sealed
  end

  def export
    cards = Card.where(id: cards_for_export)
    @cards = Exporters::Text.perform(cards)

    render 'common/export'
  end

  private

  def card_sets
    [].tap do |card_sets|
      6.times do |i|
        card_sets << params.send("[]", "set#{i+1}")
      end
    end
  end

  def cards_for_export
    params.keys.map do |key|
      key.gsub("checkbox_", "")
    end
  end
end

app/views/sealeds/new.html.erb
<h2>Generate Sealed</h2>
<%= form_tag controller: :sealeds, action: :create, method: :post do %>
  <%= select_tag :set1, options_from_collection_for_select(@sets, :id, :name), class: 'ui search dropdown' %>
  <br />
  <%= select_tag :set2, options_from_collection_for_select(@sets, :id, :name), class: 'ui search dropdown' %>
  <br />
  <%= select_tag :set3, options_from_collection_for_select(@sets, :id, :name), class: 'ui search dropdown' %>
  <br />
  <%= select_tag :set4, options_from_collection_for_select(@sets, :id, :name), class: 'ui search dropdown' %>
  <br />
  <%= select_tag :set5, options_from_collection_for_select(@sets, :id, :name), class: 'ui search dropdown' %>
  <br />
  <%= select_tag :set6, options_from_collection_for_select(@sets, :id, :name), class: 'ui search dropdown' %>
  <br />
  <br />
  <%= button_tag t(".get_cards"), class: "ui black button" %>
<% end %>

app/views/sealeds/show.html.erb
<%= form_for @sealed, url: export_sealed_path(@sealed), method: "post" do |f| %>
  <div class="ui grid">
    <div class="thirteen wide column">
      <div class="ui container">
        <%= render "common/card", cards: @cards %>
      </div>
    </div>
    <div class="three wide column centered">
      <div class="ui container center aligned">
        <%= f.button type: :submit, class: "ui black basic button" %>
      </div>
      <div class="ui vertical following fluid accordion text menu">
        <div class="item">
          <a class="title">
            <i class="dropdown icon"></i>
            <h3><%= t ".deck", count: @cards.count %></h3>
          </a>
          <div class="js-deck content menu active">
            <% @cards.each do |card| %>
              <p class="js-side-deck side-card card-preview" data-thumbnail-src=<%= card.image_url %> data-id=<%= card.id %>>
                <%= card.name %>
                <%= image_tag card.image_url %>
              </p>
            <% end %>
          </div>
        </div>
        <div class="item">
          <a class="title">
            <i class="dropdown icon"></i>
            <h3><%= t ".junk", count: 0 %></h3>
          </a>
          <div class="js-junk content menu active">
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>