config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'home#index'
  mount Sidekiq::Web => '/sidekiq'
  resources :decks do
    post :search
    get :card_types
    get :mana_curve
    get :color_distribution
  end
  resources :drafts
  resources :lobbies

  resources :boosters do
    post :export, on: :member
  end

  resources :sealeds do
    post :export, on: :member
  end

  resources :cards

  get 'auth/google', to: redirect('/auth/google_oauth2')
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/card.rb
class Card < ApplicationRecord
  include PgSearch

  MULTIVERSE_CARD_BASE_URL = "http://gatherer.wizards.com/Pages/Card/Details.aspx".freeze
  ATTRIBUTES_FROM_API_CARD = %i[
    name mana_cost cmc colors supertypes subtypes rarity text flavor
    power toughness loyalty rulings image_url set set_name multiverse_id
  ].freeze
  CARD_COLORS = %w[Black Blue Green Red White].freeze

  belongs_to :booster, optional: true
  belongs_to :sealed, optional: true

  has_many :deck_cards
  has_many :decks, through: :deck_cards

  pg_search_scope :card_type_full_text_search, against: :card_type,
                                               using: { tsearch: { prefix: true } },
                                               order_within_rank: "cards.colors"
  pg_search_scope :full_text_search,
                  against: {
                    name: "A",
                    subtypes: "B",
                    text: "C"
                  },
                  using: { tsearch: { prefix: true } },
                  order_within_rank: "cards.colors"

  def self.build_from_api_card(template)
    Card.new.tap do |new_card|
      ATTRIBUTES_FROM_API_CARD.map do |attr|
        attribute = template.send(attr)
        new_card.send("#{attr}=", attribute)
      end
      new_card.card_type = template.type
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @search = CardsSearch.new(search_params)
    @cards = @search.results.page(params[:page]).decorate

    respond_to do |format|
      format.html
      format.json { render json: @cards }
    end
  end

  def show
    @card = Card.find(params[:id]).decorate
  end

  private

  def search_params
    params.fetch(:cards_search) { {} }
  end
end

app/helpers/cards_helper.rb
module CardsHelper
  def options_for_colors_select
    {}.tap do |opts|
      Card::CARD_COLORS.map do |color|
        opts[color] = color
      end
    end
  end
end

app/views/cards/_card.html.erb
<div class='column'>
  <div class='card' id=<%= "card_#{card.id}" %> data-id=<%= card.id %>>
    <%= link_to card_path(card) do %>
      <img class="card-image" src=<%=card.image_url %>></img>
    <% end %>
  </div>
</div>

app/views/cards/index.html.erb
<%= form_for @search, url: cards_path, method: "get", html: { class: "ui form" } do |f| %>

  <div class="fields">
    <div class="field">
      <%= f.label :full_text_search %>
      <%= f.text_field :full_text_search %>
    </div>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="fields">
    <div class="field">
      <%= f.label :card_type %>
      <%= f.text_field :card_type %>
    </div>

    <br />
    <div class="field">
      <%= f.label :colors  %>
      <%= f.select :colors, options_for_colors_select, {}, class: "ui search dropdown", multiple: "" %>
    </div>

    <div class="field">
      <%= f.label :cmc %>
      <%= f.select :cmc, options_for_select(0..17), { include_blank: true }, class: "ui compact search dropdown" %>
    </div>
  </div>
  <br />
  <%= f.submit "Search" %>
<% end %>

<div class='cards ui stackable five column grid container'>
  <%= render partial: "card", collection: @cards %>
  <%= paginate @cards %>
</div>

app/views/cards/show.html.erb
<div class='card' id=<%= "card_#{@card.id}" %> data-id=<%= @card.id %>>
  <a href=<%= @card.multiverse_url %>><%= "#{@card.name} #{@card.mana_cost}"%></a>
  <p class='card-type'><%= @card.card_type %></p>
  <img src=<%=@card.image_url %>></img>
</div>