config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'home#index'
  mount Sidekiq::Web => '/sidekiq'
  resources :decks do
    post :search
    get :card_types
    get :mana_curve
    get :color_distribution
  end
  resources :drafts
  resources :lobbies

  resources :boosters do
    post :export, on: :member
  end

  resources :sealeds do
    post :export, on: :member
  end

  resources :cards

  get 'auth/google', to: redirect('/auth/google_oauth2')
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booster.rb
class Booster < ApplicationRecord
  belongs_to :card_set, optional: true
  belongs_to :draft, optional: true

  has_many :cards, dependent: :destroy
end

app/models/card.rb
class Card < ApplicationRecord
  include PgSearch

  MULTIVERSE_CARD_BASE_URL = "http://gatherer.wizards.com/Pages/Card/Details.aspx".freeze
  ATTRIBUTES_FROM_API_CARD = %i[
    name mana_cost cmc colors supertypes subtypes rarity text flavor
    power toughness loyalty rulings image_url set set_name multiverse_id
  ].freeze
  CARD_COLORS = %w[Black Blue Green Red White].freeze

  belongs_to :booster, optional: true
  belongs_to :sealed, optional: true

  has_many :deck_cards
  has_many :decks, through: :deck_cards

  pg_search_scope :card_type_full_text_search, against: :card_type,
                                               using: { tsearch: { prefix: true } },
                                               order_within_rank: "cards.colors"
  pg_search_scope :full_text_search,
                  against: {
                    name: "A",
                    subtypes: "B",
                    text: "C"
                  },
                  using: { tsearch: { prefix: true } },
                  order_within_rank: "cards.colors"

  def self.build_from_api_card(template)
    Card.new.tap do |new_card|
      ATTRIBUTES_FROM_API_CARD.map do |attr|
        attribute = template.send(attr)
        new_card.send("#{attr}=", attribute)
      end
      new_card.card_type = template.type
    end
  end
end

app/models/card_set.rb
class CardSet < ApplicationRecord
  has_many :blocks
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :deck_cards, dependent: :destroy
  has_many :cards, through: :deck_cards
end

app/models/deck_card.rb
class DeckCard < ApplicationRecord
  belongs_to :deck
  belongs_to :card
end

app/models/draft.rb
class Draft < ApplicationRecord
  belongs_to :lobby

  has_many :boosters
  has_many :users
end

app/models/lobby.rb
class Lobby < ApplicationRecord
  has_many :drafts
  has_many :users
end

app/models/sealed.rb
class Sealed < ApplicationRecord
  has_many :card_set
  has_many :cards, dependent: :destroy

  def ordered_cards
    cards.order(:colors, :cmc, :name)
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :lobby, optional: true
  belongs_to :draft, optional: true

  def self.find_or_create_from_auth_hash(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.email = auth.info.email
      user.picture = auth.info.image
      user.save!
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @search = CardsSearch.new(search_params)
    @cards = @search.results.page(params[:page]).decorate

    respond_to do |format|
      format.html
      format.json { render json: @cards }
    end
  end

  def show
    @card = Card.find(params[:id]).decorate
  end

  private

  def search_params
    params.fetch(:cards_search) { {} }
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def show
    deck = Deck.find(params[:id])
    @cards = deck.cards.decorate
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = Deck.new(deck_params)
    @deck.save
  end

  # Extract to some other controller later
  # Extract logic to a service
  def card_types
    cards = Deck.find(params[:deck_id]).cards
    @types = {}
    cards.group(:types).count.map do |type, count|
      joined_type = type.join(" ")
      @types[joined_type] = count
    end
    respond_to do |format|
      format.js { render json: @types }
    end
  end

  # Extract to some other controller later
  # Extract logic to a service
  def mana_curve
    cards = Deck.find(params[:deck_id]).cards
    @mana_costs = cards.where.not("types @> ARRAY[?]", "Land").group(:cmc).count
    respond_to do |format|
      format.js { render json: @mana_costs }
    end
  end

  # Extract to some other controller later
  # Extract logic to a service
  def color_distribution
    @colors = {}
    color_distribution = Deck.find(params[:deck_id]).cards.group(:colors).count
    @colors["Colorless"] = color_distribution[nil]
    color_distribution.delete(nil)
    color_distribution.map do |color, count|
      joined_colors = color.join(" / ")
      @colors[joined_colors] = count
    end
    respond_to do |format|
      format.js { render json: @colors }
    end
  end

  private

  def deck_params
    params.require(:deck).permit(:name)
  end
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  def create
    @draft = Draft.create(draft_params)
    booster_set_ids.map do |set_id|
      Boosters::Create.new(set_id, @draft.id).perform
    end
  end

  private

  def draft_params
    params.require(:draft).permit(:lobby_id)
  end
  
  def booster_set_ids
    params.select { |k, _| k.starts_with?("booster") }.values
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate

  def index; end
end

app/controllers/lobbies_controller.rb
class LobbiesController < ApplicationController
  def new
    @form = LobbyForm.new
  end

  def show
    @lobby = Lobby.find(params[:id]).decorate
  end

  def create
    @form = LobbyForm.new(lobby_params)
    @form.save

    redirect_to @form
  end

  private

  def lobby_params
    params.require(:lobby).permit(:name, :game_type, :number_of_players).to_h
  end
end

app/controllers/sealeds_controller.rb
class SealedsController < ApplicationController
  def new
    @sets = CardSet.where(set_type: 'expansion').order(release_date: :desc)
  end

  def show
    @sealed = Sealed.find(params[:id])
    @cards = @sealed.ordered_cards
  end

  def create
    sealed = Sealed.create
    @cards = Sealeds::Create.perform(card_sets, sealed)

    redirect_to sealed
  end

  def export
    cards = Card.where(id: cards_for_export)
    @cards = Exporters::Text.perform(cards)

    render 'common/export'
  end

  private

  def card_sets
    [].tap do |card_sets|
      6.times do |i|
        card_sets << params.send("[]", "set#{i+1}")
      end
    end
  end

  def cards_for_export
    params.keys.map do |key|
      key.gsub("checkbox_", "")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(target_controller)
    return 'active' if params[:controller] == target_controller.to_s
  end
end

app/helpers/cards_helper.rb
module CardsHelper
  def options_for_colors_select
    {}.tap do |opts|
      Card::CARD_COLORS.map do |color|
        opts[color] = color
      end
    end
  end
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/helpers/lobbies_helper.rb
module LobbiesHelper
  def render_game_setup(lobby)
    partial = determine_partial(lobby)
    render partial, object: lobby.game_object, sets: lobby.sets
  end

  private

  def determine_partial(lobby)
    "#{lobby.game_type.downcase}s/new" 
  end
end

app/views/common/_card.html.erb
<div class='cards ui stackable four column grid container'>
  <% cards.each do |card| %>
    <div class='column'>
      <div class='card' id=<%= "card_#{card.id}" %> data-id=<%= card.id %>>
        <%= link_to "#{card.name} #{card.mana_cost}", card.multiverse_url, class: 'card-name' %>
        <p class='card-type'><%= card.card_type %></p>
        <%= image_tag card.image_url, id: "image_#{card.id}", class: 'card-image' %>
        <%= check_box_tag "checkbox_#{card.id}", '1', true, class: 'hidden', 'data-id': card.id %>
      </div>
    </div>
  <% end %>
</div>

app/views/common/export.html.erb
<% @cards.each do |name, quantity| %>
  <%= quantity %>
  <%= name %>
  <br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MTG Draft</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%#<%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <header class="top-bar ui secondary pointing segment menu">
      <% if current_user %>
        <%= link_to "New Lobby", new_lobby_path, class: "item #{active_class(:lobbies)}" %>
        <%= link_to "New Sealed", new_sealed_path, class: "item #{active_class(:sealeds)}" %>
        <div class="right menu">
          <div class="ui pointing dropdown link item">
            <span class="text">
              <img class="ui avatar image" src="<%= current_user.picture %>">
              <span>
                <%= "#{current_user.first_name} #{current_user.last_name}" %>
              </span>
            </span>
            <i class="dropdown icon"></i>
            <div class="menu">
              <div class="item">
                <a class="ui item" href="/logout">
                  Logout
                </a>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <a href="/auth/google">Sign in with Google</a>
      <% end %>
    </header>
    <main>
    <%= yield %>
    </main>
  </body>
</html>